/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as FlagsIndexRouteImport } from './routes/flags.index';
import { Route as OrgOpsIndexRouteImport } from './routes/org-ops.index';
import { Route as OrgsIndexRouteImport } from './routes/orgs.index';
import { Route as ServiceControlIndexRouteImport } from './routes/service-control.index';
import { Route as FlagsFlagIndexRouteImport } from './routes/flags.$flag.index';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const FlagsIndexRoute = FlagsIndexRouteImport.update({
  id: '/flags/',
  path: '/flags/',
  getParentRoute: () => rootRouteImport,
} as any);
const OrgOpsIndexRoute = OrgOpsIndexRouteImport.update({
  id: '/org-ops/',
  path: '/org-ops/',
  getParentRoute: () => rootRouteImport,
} as any);
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => rootRouteImport,
} as any);
const ServiceControlIndexRoute = ServiceControlIndexRouteImport.update({
  id: '/service-control/',
  path: '/service-control/',
  getParentRoute: () => rootRouteImport,
} as any);
const FlagsFlagIndexRoute = FlagsFlagIndexRouteImport.update({
  id: '/flags/$flag/',
  path: '/flags/$flag/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/flags/': typeof FlagsIndexRoute;
  '/org-ops/': typeof OrgOpsIndexRoute;
  '/orgs/': typeof OrgsIndexRoute;
  '/service-control/': typeof ServiceControlIndexRoute;
  '/flags/$flag/': typeof FlagsFlagIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/flags': typeof FlagsIndexRoute;
  '/org-ops': typeof OrgOpsIndexRoute;
  '/orgs': typeof OrgsIndexRoute;
  '/service-control': typeof ServiceControlIndexRoute;
  '/flags/$flag': typeof FlagsFlagIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/flags/': typeof FlagsIndexRoute;
  '/org-ops/': typeof OrgOpsIndexRoute;
  '/orgs/': typeof OrgsIndexRoute;
  '/service-control/': typeof ServiceControlIndexRoute;
  '/flags/$flag/': typeof FlagsFlagIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/flags/' | '/org-ops/' | '/orgs/' | '/service-control/' | '/flags/$flag/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/flags' | '/org-ops' | '/orgs' | '/service-control' | '/flags/$flag';
  id: '__root__' | '/' | '/flags/' | '/org-ops/' | '/orgs/' | '/service-control/' | '/flags/$flag/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  FlagsIndexRoute: typeof FlagsIndexRoute;
  OrgOpsIndexRoute: typeof OrgOpsIndexRoute;
  OrgsIndexRoute: typeof OrgsIndexRoute;
  ServiceControlIndexRoute: typeof ServiceControlIndexRoute;
  FlagsFlagIndexRoute: typeof FlagsFlagIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/flags/': {
      id: '/flags/';
      path: '/flags';
      fullPath: '/flags/';
      preLoaderRoute: typeof FlagsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/org-ops/': {
      id: '/org-ops/';
      path: '/org-ops';
      fullPath: '/org-ops/';
      preLoaderRoute: typeof OrgOpsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/orgs/': {
      id: '/orgs/';
      path: '/orgs';
      fullPath: '/orgs/';
      preLoaderRoute: typeof OrgsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/service-control/': {
      id: '/service-control/';
      path: '/service-control';
      fullPath: '/service-control/';
      preLoaderRoute: typeof ServiceControlIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/flags/$flag/': {
      id: '/flags/$flag/';
      path: '/flags/$flag';
      fullPath: '/flags/$flag/';
      preLoaderRoute: typeof FlagsFlagIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlagsIndexRoute: FlagsIndexRoute,
  OrgOpsIndexRoute: OrgOpsIndexRoute,
  OrgsIndexRoute: OrgsIndexRoute,
  ServiceControlIndexRoute: ServiceControlIndexRoute,
  FlagsFlagIndexRoute: FlagsFlagIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
