/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as EmailIndexRouteImport } from './routes/email.index';
import { Route as FlagsIndexRouteImport } from './routes/flags.index';
import { Route as MigrationsIndexRouteImport } from './routes/migrations.index';
import { Route as OrgOpsIndexRouteImport } from './routes/org-ops.index';
import { Route as OrgsIndexRouteImport } from './routes/orgs.index';
import { Route as FlagsFlagIndexRouteImport } from './routes/flags.$flag.index';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const EmailIndexRoute = EmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => rootRouteImport,
} as any);
const FlagsIndexRoute = FlagsIndexRouteImport.update({
  id: '/flags/',
  path: '/flags/',
  getParentRoute: () => rootRouteImport,
} as any);
const MigrationsIndexRoute = MigrationsIndexRouteImport.update({
  id: '/migrations/',
  path: '/migrations/',
  getParentRoute: () => rootRouteImport,
} as any);
const OrgOpsIndexRoute = OrgOpsIndexRouteImport.update({
  id: '/org-ops/',
  path: '/org-ops/',
  getParentRoute: () => rootRouteImport,
} as any);
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => rootRouteImport,
} as any);
const FlagsFlagIndexRoute = FlagsFlagIndexRouteImport.update({
  id: '/flags/$flag/',
  path: '/flags/$flag/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/email/': typeof EmailIndexRoute;
  '/flags/': typeof FlagsIndexRoute;
  '/migrations/': typeof MigrationsIndexRoute;
  '/org-ops/': typeof OrgOpsIndexRoute;
  '/orgs/': typeof OrgsIndexRoute;
  '/flags/$flag/': typeof FlagsFlagIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/email': typeof EmailIndexRoute;
  '/flags': typeof FlagsIndexRoute;
  '/migrations': typeof MigrationsIndexRoute;
  '/org-ops': typeof OrgOpsIndexRoute;
  '/orgs': typeof OrgsIndexRoute;
  '/flags/$flag': typeof FlagsFlagIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/email/': typeof EmailIndexRoute;
  '/flags/': typeof FlagsIndexRoute;
  '/migrations/': typeof MigrationsIndexRoute;
  '/org-ops/': typeof OrgOpsIndexRoute;
  '/orgs/': typeof OrgsIndexRoute;
  '/flags/$flag/': typeof FlagsFlagIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/email/'
    | '/flags/'
    | '/migrations/'
    | '/org-ops/'
    | '/orgs/'
    | '/flags/$flag/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/email'
    | '/flags'
    | '/migrations'
    | '/org-ops'
    | '/orgs'
    | '/flags/$flag';
  id:
    | '__root__'
    | '/'
    | '/email/'
    | '/flags/'
    | '/migrations/'
    | '/org-ops/'
    | '/orgs/'
    | '/flags/$flag/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  EmailIndexRoute: typeof EmailIndexRoute;
  FlagsIndexRoute: typeof FlagsIndexRoute;
  MigrationsIndexRoute: typeof MigrationsIndexRoute;
  OrgOpsIndexRoute: typeof OrgOpsIndexRoute;
  OrgsIndexRoute: typeof OrgsIndexRoute;
  FlagsFlagIndexRoute: typeof FlagsFlagIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/email/': {
      id: '/email/';
      path: '/email';
      fullPath: '/email/';
      preLoaderRoute: typeof EmailIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/flags/': {
      id: '/flags/';
      path: '/flags';
      fullPath: '/flags/';
      preLoaderRoute: typeof FlagsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/migrations/': {
      id: '/migrations/';
      path: '/migrations';
      fullPath: '/migrations/';
      preLoaderRoute: typeof MigrationsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/org-ops/': {
      id: '/org-ops/';
      path: '/org-ops';
      fullPath: '/org-ops/';
      preLoaderRoute: typeof OrgOpsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/orgs/': {
      id: '/orgs/';
      path: '/orgs';
      fullPath: '/orgs/';
      preLoaderRoute: typeof OrgsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/flags/$flag/': {
      id: '/flags/$flag/';
      path: '/flags/$flag';
      fullPath: '/flags/$flag/';
      preLoaderRoute: typeof FlagsFlagIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailIndexRoute: EmailIndexRoute,
  FlagsIndexRoute: FlagsIndexRoute,
  MigrationsIndexRoute: MigrationsIndexRoute,
  OrgOpsIndexRoute: OrgOpsIndexRoute,
  OrgsIndexRoute: OrgsIndexRoute,
  FlagsFlagIndexRoute: FlagsFlagIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
