/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as FlagsIndexRouteImport } from './routes/flags.index';
import { Route as OrgsIndexRouteImport } from './routes/orgs.index';
import { Route as FlagsFlagIndexRouteImport } from './routes/flags.$flag.index';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const FlagsIndexRoute = FlagsIndexRouteImport.update({
  id: '/flags/',
  path: '/flags/',
  getParentRoute: () => rootRouteImport,
} as any);
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => rootRouteImport,
} as any);
const FlagsFlagIndexRoute = FlagsFlagIndexRouteImport.update({
  id: '/flags/$flag/',
  path: '/flags/$flag/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/flags/': typeof FlagsIndexRoute;
  '/orgs/': typeof OrgsIndexRoute;
  '/flags/$flag/': typeof FlagsFlagIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/flags': typeof FlagsIndexRoute;
  '/orgs': typeof OrgsIndexRoute;
  '/flags/$flag': typeof FlagsFlagIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/flags/': typeof FlagsIndexRoute;
  '/orgs/': typeof OrgsIndexRoute;
  '/flags/$flag/': typeof FlagsFlagIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/flags/' | '/orgs/' | '/flags/$flag/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/flags' | '/orgs' | '/flags/$flag';
  id: '__root__' | '/' | '/flags/' | '/orgs/' | '/flags/$flag/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  FlagsIndexRoute: typeof FlagsIndexRoute;
  OrgsIndexRoute: typeof OrgsIndexRoute;
  FlagsFlagIndexRoute: typeof FlagsFlagIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/flags/': {
      id: '/flags/';
      path: '/flags';
      fullPath: '/flags/';
      preLoaderRoute: typeof FlagsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/orgs/': {
      id: '/orgs/';
      path: '/orgs';
      fullPath: '/orgs/';
      preLoaderRoute: typeof OrgsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/flags/$flag/': {
      id: '/flags/$flag/';
      path: '/flags/$flag';
      fullPath: '/flags/$flag/';
      preLoaderRoute: typeof FlagsFlagIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlagsIndexRoute: FlagsIndexRoute,
  OrgsIndexRoute: OrgsIndexRoute,
  FlagsFlagIndexRoute: FlagsFlagIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
