/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CustomersOrgIdRouteImport } from './routes/customers/$orgId'
import { Route as FeatureFlagsIndexRouteImport } from './routes/feature-flags/index'
import { Route as StripeSyncIndexRouteImport } from './routes/stripe-sync/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersOrgIdRoute = CustomersOrgIdRouteImport.update({
  id: '/customers/$orgId',
  path: '/customers/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureFlagsIndexRoute = FeatureFlagsIndexRouteImport.update({
  id: '/feature-flags/',
  path: '/feature-flags/',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeSyncIndexRoute = StripeSyncIndexRouteImport.update({
  id: '/stripe-sync/',
  path: '/stripe-sync/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/customers/$orgId': typeof CustomersOrgIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/feature-flags/': typeof FeatureFlagsIndexRoute
  '/stripe-sync/': typeof StripeSyncIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/customers/$orgId': typeof CustomersOrgIdRoute
  '/customers': typeof CustomersIndexRoute
  '/feature-flags': typeof FeatureFlagsIndexRoute
  '/stripe-sync': typeof StripeSyncIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/customers/$orgId': typeof CustomersOrgIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/feature-flags/': typeof FeatureFlagsIndexRoute
  '/stripe-sync/': typeof StripeSyncIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/auth/error'
    | '/customers/$orgId'
    | '/customers/'
    | '/feature-flags/'
    | '/stripe-sync/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/auth/error'
    | '/customers/$orgId'
    | '/customers'
    | '/feature-flags'
    | '/stripe-sync'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/auth/callback'
    | '/auth/error'
    | '/customers/$orgId'
    | '/customers/'
    | '/feature-flags/'
    | '/stripe-sync/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthErrorRoute: typeof AuthErrorRoute
  CustomersOrgIdRoute: typeof CustomersOrgIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  FeatureFlagsIndexRoute: typeof FeatureFlagsIndexRoute
  StripeSyncIndexRoute: typeof StripeSyncIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$orgId': {
      id: '/customers/$orgId'
      path: '/customers/$orgId'
      fullPath: '/customers/$orgId'
      preLoaderRoute: typeof CustomersOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature-flags/': {
      id: '/feature-flags/'
      path: '/feature-flags'
      fullPath: '/feature-flags/'
      preLoaderRoute: typeof FeatureFlagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe-sync/': {
      id: '/stripe-sync/'
      path: '/stripe-sync'
      fullPath: '/stripe-sync/'
      preLoaderRoute: typeof StripeSyncIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthErrorRoute: AuthErrorRoute,
  CustomersOrgIdRoute: CustomersOrgIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  FeatureFlagsIndexRoute: FeatureFlagsIndexRoute,
  StripeSyncIndexRoute: StripeSyncIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
